// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJdNFIHcqwQ_s27oqp1KrKyEK0EkW2UQ',
    appId: '1:137514346604:web:79e61774662623eee6d049',
    messagingSenderId: '137514346604',
    projectId: 'crud-application-47610',
    authDomain: 'crud-application-47610.firebaseapp.com',
    storageBucket: 'crud-application-47610.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpS7_vkfJ3qR5SQn7430-XusDwSRTSwYk',
    appId: '1:137514346604:android:09661a4f2a908aafe6d049',
    messagingSenderId: '137514346604',
    projectId: 'crud-application-47610',
    storageBucket: 'crud-application-47610.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChziYDQvMQo_ZgYI-oc2984mIjFncVEug',
    appId: '1:137514346604:ios:51519b7c09a0ac99e6d049',
    messagingSenderId: '137514346604',
    projectId: 'crud-application-47610',
    storageBucket: 'crud-application-47610.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChziYDQvMQo_ZgYI-oc2984mIjFncVEug',
    appId: '1:137514346604:ios:51519b7c09a0ac99e6d049',
    messagingSenderId: '137514346604',
    projectId: 'crud-application-47610',
    storageBucket: 'crud-application-47610.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnJdNFIHcqwQ_s27oqp1KrKyEK0EkW2UQ',
    appId: '1:137514346604:web:c60de17c19267dfae6d049',
    messagingSenderId: '137514346604',
    projectId: 'crud-application-47610',
    authDomain: 'crud-application-47610.firebaseapp.com',
    storageBucket: 'crud-application-47610.firebasestorage.app',
  );
}
